services:
  wordpress:
    image: wordpress:latest
    container_name: wordpressdevops19
    ports:
      - "8081:80"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:5.7
    container_name: mysql_wordpress
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./apache-config.conf:/etc/apache2/conf-available/z-app.conf
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
